lib/frmwrk_web/router.ex
defmodule FrmwrkWeb.Router do
  use FrmwrkWeb, :router

  pipeline :auth do
    plug Frmwrk.Auth.Pipeline
    plug Frmwrk.Plugs.SetUser
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FrmwrkWeb do
    pipe_through [:browser, :auth] # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    # resources "/campaigns", CampaignController
  end

  scope "/campaigns", FrmwrkWeb do
    pipe_through [:browser, :auth]

    get "/", CampaignController, :index
    get "/new", CampaignController, :new
    post "/create", CampaignController, :create
    get "/:url", CampaignController, :show

    get "/:url/comment", CampaignController, :comment_new

    get "/:url/donation", DonationController, :new
    post "/:url/donation", DonationController, :create
    post "/:url/donation/:amount/:action", DonationController, :confirm
  end

  scope "/auth", FrmwrkWeb do
    pipe_through [:browser, :auth]

    get "/login", AuthController, :login
    post "/login", AuthController, :create_login

    get "/password", AuthController, :password
    post "/password", AuthController, :set_password

    get "/register", AuthController, :register
    post "/register", AuthController, :create_user

    get "/signout", AuthController, :delete
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", FrmwrkWeb do
  #   pipe_through :api
  # end
end

lib/frmwrk_web/templates/page/index.html.eex
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Frmwrk</h1>
  <p class="lead">Infaqkan sebagian harga Anda</p>
</div>

<div class="container">
  <div class="card-deck mb-3">
    <a class="card card-link" href='#' style="width: 18rem;">
      <img class="card-img-top" src="http://via.placeholder.com/350x250" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      </div>
    </a>
    <a class="card card-link" href='#' style="width: 18rem;">
      <img class="card-img-top" src="http://via.placeholder.com/350x250" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      </div>
    </a>
    <a class="card card-link" href='#' style="width: 18rem;">
      <img class="card-img-top" src="http://via.placeholder.com/350x250" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      </div>
    </a>
  </div>

  <div class="pt-4 text-center">
    <a class="btn btn-primary btn-lg" href="<%= campaign_path(@conn, :index) %>" role="button">Jelajahi</a>
  </div>

  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="<%= static_path(@conn, "/images/logo.png") %>" alt="" width="64" height="64">
        <small class="d-block mb-3 text-muted">&copy; 2017-2018</small>
      </div>
      <div class="col-6 col-md">
        <h5>Bantuan</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">FAQ</a></li>              
          <li><a class="text-muted" href="#">Berdonasi</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Tentang</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Profil</a></li>
          <li><a class="text-muted" href="#">Legal</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>