lib/frmwrk_web/router.ex
defmodule FrmwrkWeb.Router do
  use FrmwrkWeb, :router

  pipeline :auth do
    plug Frmwrk.Auth.Pipeline
    plug Frmwrk.Plugs.SetUser
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FrmwrkWeb do
    pipe_through [:browser, :auth] # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    # resources "/campaigns", CampaignController
  end

  scope "/campaigns", FrmwrkWeb do
    pipe_through [:browser, :auth]

    get "/", CampaignController, :index
    get "/new", CampaignController, :new
    post "/create", CampaignController, :create
    get "/:url", CampaignController, :show

    get "/:url/comment", CampaignController, :comment_new

    get "/:url/donation", DonationController, :new
    post "/:url/donation", DonationController, :create
    post "/:url/donation/:amount/:action", DonationController, :confirm
  end

  scope "/auth", FrmwrkWeb do
    pipe_through [:browser, :auth]

    get "/login", AuthController, :login
    post "/login", AuthController, :create_login

    get "/password", AuthController, :password
    post "/password", AuthController, :set_password

    get "/register", AuthController, :register
    post "/register", AuthController, :create_user

    get "/signout", AuthController, :delete
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", FrmwrkWeb do
  #   pipe_through :api
  # end
end

lib/frmwrk/campaigns/campaign.ex
defmodule Frmwrk.Campaigns.Campaign do
  use Ecto.Schema
  import Ecto.Changeset

  alias Frmwrk.Auth.User

  schema "campaigns" do
    field(:deadline, :date)
    field(:description, :string)
    field(:short_description, :string)
    field(:title, :string)
    field(:image, :string)
    field(:url, :string, null: false)

    belongs_to(:user, User)
    has_many(:comments, Frmwrk.Campaigns.Comment)

    timestamps()
  end

  @doc false
  def changeset(campaign, attrs) do
    campaign
    |> cast(attrs, [:title, :short_description, :description, :deadline, :image, :url])
    |> validate_required([:title, :url])
  end
end

lib/frmwrk/campaigns/campaigns.ex
defmodule Frmwrk.Campaigns do
  @moduledoc """
  The Campaigns context.
  """

  import Ecto.Query, warn: false
  import Ecto.Changeset

  alias Frmwrk.Repo

  alias Frmwrk.Campaigns.Campaign
  alias Frmwrk.Auth.User

  def list_campaigns do
    Repo.all(Campaign)
  end

  def get_campaign!(id), do: Repo.get!(Campaign, id)

  def get_campaign_by_url(url), do: Repo.get_by(Campaign, url: url)

  def create_campaign(attrs \\ %{}) do
    %Campaign{}
    |> Campaign.changeset(attrs)
    |> Repo.insert()
  end

  def update_campaign(%Campaign{} = campaign, attrs) do
    campaign
    |> Campaign.changeset(attrs)
    |> Repo.update()
  end

  def delete_campaign(%Campaign{} = campaign) do
    Repo.delete(campaign)
  end

  def change_campaign(%Campaign{} = campaign) do
    Campaign.changeset(campaign, %{})
  end

  alias Frmwrk.Campaigns.Donation

  def list_donations do
    Repo.all(Donation)
  end

  def get_donation!(id), do: Repo.get!(Donation, id)

  def create_donation(attrs \\ %{}, %Campaign{id: campaign_id}, %User{id: user_id}) do
    %Donation{}
    |> Donation.changeset(attrs)
    |> put_change(:user_id, user_id)
    |> put_change(:campaign_id, campaign_id)
    |> Donation.add_unique_number()
    |> Repo.insert()
  end

  def update_donation(%Donation{} = donation, attrs) do
    donation
    |> Donation.changeset(attrs)
    |> Repo.update()
  end

  def delete_donation(%Donation{} = donation) do
    Repo.delete(donation)
  end

  def change_donation(%Donation{} = donation) do
    Donation.changeset(donation, %{})
  end

  alias Frmwrk.Campaigns.Comment

  def list_comments do
    Repo.all(Comment)
  end

  def get_comment!(id), do: Repo.get!(Comment, id)

  def create_comment(attrs \\ %{}) do
    %Comment{}
    |> Comment.changeset(attrs)
    |> Repo.insert()
  end

  def update_comment(%Comment{} = comment, attrs) do
    comment
    |> Comment.changeset(attrs)
    |> Repo.update()
  end

  def delete_comment(%Comment{} = comment) do
    Repo.delete(comment)
  end

  def change_comment(%Comment{} = comment) do
    Comment.changeset(comment, %{})
  end
end

lib/frmwrk/campaigns/comment.ex
defmodule Frmwrk.Campaigns.Comment do
  use Ecto.Schema
  import Ecto.Changeset

  schema "comments" do
    field(:text, :string)

    belongs_to(:campaign, Frmwrk.Campaigns.Campaign)
    belongs_to(:user, Frmwrk.Auth.User)

    timestamps()
  end

  @doc false
  def changeset(comment, attrs) do
    comment
    |> cast(attrs, [:text])
    |> validate_required([:text])
  end
end

lib/frmwrk/campaigns/donation.ex
defmodule Frmwrk.Campaigns.Donation do
  use Ecto.Schema

  alias Frmwrk.Repo
  alias Ecto.Changeset

  import Ecto.Changeset
  import Ecto.Query

  schema "donations" do
    field(:amount, :integer)
    field(:verified_at, :date)
    field(:unique_number, :integer)
    field(:confirmed, :boolean)

    belongs_to(:user, Frmwrk.Auth.User)
    belongs_to(:campaign, Frmwrk.Campaigns.Campaign)

    timestamps()
  end

  # @doc false
  def changeset(donation, attrs) do
    donation
    |> cast(attrs, [:amount, :unique_number])
    |> validate_number(:amount, greater_than_or_equal_to: 20000)
  end

  def add_unique_number(%Changeset{valid?: true} = changeset) do
    unique_number = generate_unique_number()

    changeset
    |> put_change(:amount, get_field(changeset, :amount) + unique_number)
    |> put_change(:unique_number, unique_number)
  end

  def add_unique_number(%Changeset{valid?: false} = changeset), do: changeset

  def generate_unique_number() do
    unique_number = (:rand.uniform() * 1000) |> Kernel.trunc()
    query = from(d in __MODULE__, where: d.amount == ^unique_number and is_nil(d.verified_at))

    case Repo.all(query) do
      [] ->
        unique_number

      _ ->
        generate_unique_number()
    end
  end

  def donation_to_confirm(amount) do
    query = from(d in __MODULE__, where: d.amount == ^amount and is_nil(d.confirmed))

    case Repo.all(query) do
      [campaign | _] ->
        campaign

      _ ->
        nil
    end
  end

  def confirm_donation(%__MODULE__{} = donation, "approve") do
    donation
    |> Ecto.Changeset.change(confirmed: true)
    |> Repo.update()
  end

  def confirm_donation(%__MODULE__{} = donation, "cancel") do
    donation
    |> Repo.delete()
  end
end

lib/frmwrk_web/controllers/campaign_controller.ex
defmodule FrmwrkWeb.CampaignController do
  use FrmwrkWeb, :controller

  alias Frmwrk.Campaigns
  alias Frmwrk.Campaigns.Campaign

  def index(conn, _params) do
    campaigns = Campaigns.list_campaigns()
    render(conn, "index.html", campaigns: campaigns)
  end

  def new(conn, _params) do
    changeset = Campaigns.change_campaign(%Campaign{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"campaign" => campaign_params}) do
    case Campaigns.create_campaign(campaign_params) do
      {:ok, campaign} ->
        conn
        |> put_flash(:info, "Campaign created successfully.")
        |> redirect(to: campaign_path(conn, :show, campaign.url))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:error, "Data tidak sesuai")
        |> render("new.html", changeset: changeset)
    end
  end

  def show(conn, %{"url" => url}) do
    case Campaigns.get_campaign_by_url(url) do
      nil ->
        conn
        |> put_flash(:error, "Kampanye tidak ditemukan")
        |> redirect(to: campaign_path(conn, :index))

      campaign ->
        render(conn, "show.html", campaign: campaign)
    end
  end

  def update(conn, %{"id" => id, "campaign" => campaign_params}) do
    campaign = Campaigns.get_campaign!(id)

    case Campaigns.update_campaign(campaign, campaign_params) do
      {:ok, campaign} ->
        conn
        |> put_flash(:info, "Campaign updated successfully.")
        |> redirect(to: campaign_path(conn, :show, campaign))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", campaign: campaign, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    campaign = Campaigns.get_campaign!(id)
    {:ok, _campaign} = Campaigns.delete_campaign(campaign)

    conn
    |> put_flash(:info, "Campaign deleted successfully.")
    |> redirect(to: campaign_path(conn, :index))
  end
end

lib/frmwrk_web/views/campaign_view.ex
defmodule FrmwrkWeb.CampaignView do
  use FrmwrkWeb, :view
end

lib/frmwrk_web/templates/campaign/donation_confirm.html.eex
<div class="container text-center">
  <h2 class="text-center mt-5">Konfirmasi</h2>
  <p>Donasi yang harus Anda kirim adalah sejumlah</p>
  <h1>Rp. <%= @donation.amount %>,00</h1>

  <p>Kami menambahkan Rp. <%= @donation.unique_number %>,00 sebagai kode konfirmasi.</p>
  <p>Kode tersebut digunakan untuk konfirmasi transfer otomatis</p>
  <p>Anda tidak perlu konfirmasi manual</p>
  <p class="mt-4">Apakah Anda mengkonfirmasi biaya tersebut?</p>
  <%= link "Batal",
      to: campaign_path(@conn, :donation_confirm,
          @campaign.url, @donation.amount, :cancel),
      method: :post,
      class: "btn btn-outline-primary"
  %>
  <%= link "Konfirmasi", 
      to: campaign_path(@conn, :donation_confirm, 
          @campaign.url, @donation.amount, :approve), 
      method: :post,
      class: "btn btn-primary" %>
</div>

lib/frmwrk_web/templates/campaign/donation_new.html.eex
<div class="container text-center">
  <h2 class="text-center mt-5">Masukkan Nominal</h2>
  <%= form_for @changeset, campaign_path(@conn, :donation_create, @campaign.url), fn f -> %>
    <div class="input-group input-group-lg mb-2 mt-5" style="width: 500px; margin: auto;">
      <div class="input-group-prepend">
        <span class="input-group-text">Rp.</span>
      </div>
      <%= text_input f, :amount, class: "form-control" %>
      <div class="input-group-append">
        <span class="input-group-text">,00</span>
      </div>
    </div>
    <div class="text-muted">Masukkan nominal diatas Rp 20.000,00</div>
    <div class="text-center">
      <%= submit "Donasi", class: "btn btn-primary btn-lg mt-5" %>
    </div>
  <% end %>
</div>

lib/frmwrk_web/templates/campaign/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :short_description, class: "control-label" %>
    <%= text_input f, :short_description, class: "form-control" %>
    <%= error_tag f, :short_description %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= label f, :deadline, class: "control-label" %>
    <%= date_select f, :deadline, class: "form-control" %>
    <%= error_tag f, :deadline %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/frmwrk_web/templates/campaign/index.html.eex
<div class="container">
  <h1 class="text-center">Lihat Kampanye</h1>
  <div class="card-deck mb-3 mt-5">
    <%= for campaign <- @campaigns do %>
      <a class="card card-link" href='<%= campaign_path(@conn, :show, campaign.url) %>' style="width: 18rem;">
        <img class="card-img-top" src="http://via.placeholder.com/350x250" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title"><%= campaign.title %></h5>
          <p class="card-text"><%= campaign.short_description %></p>
        </div>
      </a>
    <% end %>
  </div>
</div>

<span><%= link "New Campaign", to: campaign_path(@conn, :new) %></span>

lib/frmwrk_web/templates/campaign/new.html.eex
<div class="container">
  <h1 class="text-center">Membuat campaign</h1>
  <%= form_for @changeset, campaign_path(@conn, :create), fn f -> %>
    <div class="form-group">
      <label for="title">Judul Donasi</label>
      <%= text_input f, :title, class: "form-control" %>
      <small class="form-text text-muted">Contoh: Pembuatan Pesantren IT</small>
    </div>
    <div class="form-group">
      <label for="short_description">Deskripsi Singkat</label>
      <%= text_input f, :short_description, class: "form-control" %>
      <small class="form-text text-muted">Deskripsikan secara ringkas dari program</small>      
    </div>
    <div class="form-group">
      <label for="description">Deskripsi</label>
      <%= textarea f, :description, [class: "form-control", rows: "4"] %>
      <small class="form-text text-muted">Deskripsikan secara rinci program donasi apa yang diajukan</small>      
    </div>
    <div class="form-group">
      <label for="image_url">Alamat gambar</label>
      <%= text_input f, :image, class: "form-control" %>
      <small class="form-text text-muted">Contoh: http://test.com/donasi.png</small>
    </div>
    <div class="form-group">
      <label for="url">Alamat URL singkat</label>
      <%= text_input f, :url, class: "form-control" %>
      <small class="form-text text-muted">Masukkan alamat URL singkat sehingga mudah diakses, contoh: pesantrenit, maka dapat diakses dengan http://frmwrk.com/pesantrenit</small>
    </div>
    <div class="form-group">
      <label for="campaign_deadline">Deadline</label>
      <%= text_input f, :deadline, class: "datepicker form-control" %>
      <small class="form-text text-muted">Waktu maksimal kampanye terpenuhi</small>
    </div>
    <%= submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

lib/frmwrk_web/templates/campaign/show.html.eex
<div class='container'>
  <div class="row">
    <div class="col-md-8">
      <h1><%= @campaign.title %></h1>
      <p class="lead"><%= @campaign.short_description %></p>
      <img class="card-img-top" src="http://via.placeholder.com/350x250">
    </div>
    <div class="col-sm">
      <div class="d-none d-md-block" style="height: 5em;"></div>
      <div>
        <h2 class="mt-4">35%</h2>
        <span class="lead">tercapai</span>
        <h2 class="mt-4">Rp 3.120.000,-</h2>
        <span class="lead">dari target Rp 10.000.000,-</span>
        <a href="<%= donation_path(@conn, :new, @campaign.url)%>" role="button" class="btn btn-primary btn-lg btn-block mt-4">Donate</a>
      </div>
    </div>
  </div>
</div>
<div class="container mt-4">
  <nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Deskripsi</a>
      <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Komentar</a>
    </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
      <div class="comment-card mt-4 mb-2">
        <div class="row">
          <div class="col" style="flex-grow: 0;">
            <div class="comment-card-head">
              <img class="card-img-top" style="width:50px; height:50px;" src="http://via.placeholder.com/350x250">
            </div>
          </div>
          <div class="col text-left">
            <div class="h6">Jeff Jeff</div>
            <div>
              Ut velit asperiores dolores nemo. Sed ipsam voluptate dolores vero. Aut aut voluptate doloremque totam. Iusto maiores repudiandae perspiciatis sed eligendi non. 
            </div>
          </div>
        </div>
      </div>
      <div class="comment-card mt-4 mb-2">
        <div class="row">
          <div class="col" style="flex-grow: 0;">
            <div class="comment-card-head">
              <img class="card-img-top" style="width:50px; height:50px;" src="http://via.placeholder.com/350x250">
            </div>
          </div>
          <div class="col text-left">
            <div class="h6">Jeff Jeff</div>
            <div>
              Ut velit asperiores dolores nemo. Sed ipsam voluptate dolores vero. Aut aut voluptate doloremque totam. Iusto maiores repudiandae perspiciatis sed eligendi non. 
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
      <div class="mt-4 text-justify">
        <%= @campaign.description %>
      </div>
    </div>
  </div>
</div>

<span><%= link "Back", to: campaign_path(@conn, :index) %></span>